--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Rushil13579/ItemCooldowns
build-by-default: true
branches:
- main
projects:
  ItemCooldowns:
    path: ""
    icon: Logo.png
    
...
